#!/usr/bin/env bash
# performing a 301 move permanenetly

sudo apt-get update
sudo apt-get install -y nginx

echo "Hello World!" | sudo tee /var/www/html/index.html
strg_for_replacement="server_name _;\n\trewrite ^\//redirect_me https:\/\/github.com\/oodafeisrael permanent;"

sudo sed -i "s/server_name _;/$strg_for_replacement/" /etc/nginx/sites-enabled/default

sudo service nginx restart 
